<?php

/**
 * Asset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Asset extends BaseAsset {

    public function preHydrate(Doctrine_Event $event) {
        $data = $event->data;
        if (isset($data['node_id'])) {

            $data['asset_path'] = Doctrine_Core::getTable('Node')->find($data['node_id'])->getPath();
            $data['asset_path_3_niveles'] = $this->Mostrar3Ultimos($data['asset_path']);
            $data['asset_path_4_niveles'] = $this->Mostrar4Ultimos($data['asset_path']);
            $event->data = $data;
        }
    }

    function Mostrar3Ultimos($rutaOriginal) {

        $ruta = explode("/", $rutaOriginal);
        $count = count($ruta);

        if ($count > 3) {
            $rutaNueva = $ruta[$count - 3] . '/' . $ruta[$count - 2] . '/' . $ruta[$count - 1];
        } else {
            $rutaNueva = $rutaOriginal;
        }
        return $rutaNueva;
    }

    function Mostrar4Ultimos($rutaOriginal) {

        $ruta = explode("/", $rutaOriginal);
        $count = count($ruta);

        if ($count > 4) {
            $rutaNueva = $ruta[$count - 4] . '/' . $ruta[$count - 3] . '/' . $ruta[$count - 2] . '/' . $ruta[$count - 1];
        } else {
            $rutaNueva = $rutaOriginal;
        }
        return $rutaNueva;
    }

}
