<?php

/**
 * CostsMonth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class CostsMonth extends BaseCostsMonth {

    public function preHydrate(Doctrine_Event $event) {

        $data = $event->data;
        $CI = & get_instance();

        $january = $CI->translateTag('General', 'january');
        $february = $CI->translateTag('General', 'february');
        $march = $CI->translateTag('General', 'march');
        $april = $CI->translateTag('General', 'april');
        $may = $CI->translateTag('General', 'may');
        $june = $CI->translateTag('General', 'june');
        $july = $CI->translateTag('General', 'july');
        $august = $CI->translateTag('General', 'august');
        $september = $CI->translateTag('General', 'september');
        $october = $CI->translateTag('General', 'october');
        $november = $CI->translateTag('General', 'november');
        $december = $CI->translateTag('General', 'december');

        if ($data['costs_month_id'] == 1) {
            $mesaux = $CI->translateTag('General', 'january');
        }
        if ($data['costs_month_id'] == 2) {
            $mesaux = $CI->translateTag('General', 'february');
        }
        if ($data['costs_month_id'] == 3) {
            $mesaux = $CI->translateTag('General', 'march');
        }
        if ($data['costs_month_id'] == 4) {
            $mesaux = $CI->translateTag('General', 'april');
        }
        if ($data['costs_month_id'] == 5) {
            $mesaux = $CI->translateTag('General', 'may');
        }
        if ($data['costs_month_id'] == 6) {
            $mesaux = $CI->translateTag('General', 'june');
        }
        if ($data['costs_month_id'] == 7) {
            $mesaux = $CI->translateTag('General', 'july');
        }
        if ($data['costs_month_id'] == 8) {
            $mesaux = $CI->translateTag('General', 'august');
        }
        if ($data['costs_month_id'] == 9) {
            $mesaux = $CI->translateTag('General', 'september');
        }
        if ($data['costs_month_id'] == 10) {
            $mesaux = $CI->translateTag('General', 'october');
        }
        if ($data['costs_month_id'] == 11) {
            $mesaux = $CI->translateTag('General', 'november');
        }
        if ($data['costs_month_id'] == 12) {
            $mesaux = $CI->translateTag('General', 'december');
        }


        $data['mes_traducido'] = $mesaux;
        $event->data = $data;
    }

}
