<?php

/**
 * DocVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class DocVersion extends BaseDocVersion
{
     public function preHydrate(Doctrine_Event $event) {
        $CI = & get_instance();

        $data = $event->data;
        $extensiones_permitidas = $CI->config->item('doc_image_web');
        
        $file_extension = $CI->app->getFileExtension($data['doc_version_filename']);
        $data['doc_image_web'] = (in_array(strtoupper($file_extension), $extensiones_permitidas) ? 1 : 0);

        $event->data = $data;
    }
}
