<?php

/**
 * InfraInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 */
class InfraInfo extends BaseInfraInfo {

    var $allowListener = false;

    function getTotalArea($node_id) {

        $sum = Doctrine_Query::create()
                ->select('SUM(infra_info_area +  infra_info_area_total)')
                ->from('Node n')
                ->innerJoin('n.InfraInfo iff')
                ->where('n.node_id != ?', $node_id)
                ->groupBy('n.node_parent_id');

        $treeObject = Doctrine_Core::getTable('Node')->getTree();
        $treeObject->setBaseQuery($sum);
        $tree = $treeObject->fetchBranch($node_id, array('depth' => 1));
        $result = $tree->getFirst();

        return $result->SUM;
    }

    function getTotalUsableArea($node_id) {

        $sum = Doctrine_Query::create()
                ->select('SUM(infra_info_usable_area +  infra_info_usable_area_total)')
                ->from('Node n')
                ->innerJoin('n.InfraInfo iff')
                ->where('n.node_id != ?', $node_id)
                ->groupBy('n.node_parent_id');

        $treeObject = Doctrine_Core::getTable('Node')->getTree();
        $treeObject->setBaseQuery($sum);
        $tree = $treeObject->fetchBranch($node_id, array('depth' => 1));
        $result = $tree->getFirst();

        return $result->SUM;
    }

    function getTotalVolume($node_id) {

        $sum = Doctrine_Query::create()
                ->select('SUM(infra_info_volume +  infra_info_volume_total)')
                ->from('Node n')
                ->innerJoin('n.InfraInfo iff')
                ->where('n.node_id != ?', $node_id)
                ->groupBy('n.node_parent_id');

        $treeObject = Doctrine_Core::getTable('Node')->getTree();
        $treeObject->setBaseQuery($sum);
        $tree = $treeObject->fetchBranch($node_id, array('depth' => 1));
        $result = $tree->getFirst();

        return $result->SUM;
    }

    function getTotalCapacity($node_id) {

        $sum = Doctrine_Query::create()
                ->select('SUM(infra_info_capacity +  infra_info_capacity_total)')
                ->from('Node n')
                ->innerJoin('n.InfraInfo iff')
                ->where('n.node_id != ?', $node_id)
                ->groupBy('n.node_parent_id');

        $treeObject = Doctrine_Core::getTable('Node')->getTree();
        $treeObject->setBaseQuery($sum);
        $tree = $treeObject->fetchBranch($node_id, array('depth' => 1));
        $result = $tree->getFirst();

        return $result->SUM;
    }

    function getTotalAreaTerrain($node_id) {

        $sum = Doctrine_Query::create()
                ->select('SUM(infra_info_terrain_area +  infra_info_terrain_area_total)')
                ->from('Node n')
                ->innerJoin('n.InfraInfo iff')
                ->where('n.node_id != ?', $node_id)
                ->groupBy('n.node_parent_id');

        $treeObject = Doctrine_Core::getTable('Node')->getTree();
        $treeObject->setBaseQuery($sum);
        $tree = $treeObject->fetchBranch($node_id, array('depth' => 1));
        $result = $tree->getFirst();

        return $result->SUM;
    }

    /*function getTotalValorizacion($node_id) {
        $sum = Doctrine_Query::create()
                ->select('SUM(infra_info_terrain_area +  infra_info_terrain_area_total)')
                ->from('Node n')
                ->innerJoin('n.InfraInfo iff')
                ->where('n.node_id != ?', $node_id)
                ->groupBy('n.node_parent_id');

        $treeObject = Doctrine_Core::getTable('Node')->getTree();
        $treeObject->setBaseQuery($sum);
        $tree = $treeObject->fetchBranch($node_id, array('depth' => 1));
        $result = $tree->getFirst();

        return $result->SUM;
    }*/

    function postUpdate() {

        if (!$this->allowListener){
            return;
        }

        $fieldMapping = array(
            'infra_info_area' => 'getTotalArea',
            'infra_info_usable_area' => 'getTotalUsableArea',
            'infra_info_volume' => 'getTotalVolume',
            'infra_info_capacity' => 'getTotalCapacity',
            'infra_info_terrain_area' => 'getTotalAreaTerrain'
            //,'infra_valozacion' => 'getTotalValorizacion'
        );

        $node = Doctrine_Core::getTable('Node')->find($this->node_id)->getNode();
        if ($node->hasParent()) {
            foreach (array_reverse($node->getAncestors()->toArray()) as $ancestor) {
                $ancestorInfo = Doctrine_Core::getTable('InfraInfo')->findByNodeId($ancestor['node_id']);
                if ($ancestorInfo === false) {
                    $ancestorInfo = new InfraInfo();
                    $ancestorInfo->node_id = $ancestor['node_id'];
                }

                foreach ($fieldMapping as $att => $val) {
                    $ancestorInfo->{$att . '_total'} = $this->{$fieldMapping[$att]}($ancestor['node_id']);
                }

                $ancestorInfo->save();
            }
        }
    }

    function postInsert() {

        $this->postUpdate();
    }

    function postDelete() {

        $this->postUpdate();
    }

}
