<?php

/**
 * MtnNodeBudgetTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class MtnNodeBudgetTask extends BaseMtnNodeBudgetTask {


	function postUpdate () {
		
		$this->updateTotal();
		
	}
	
	function postInsert () {
		
		$this->updateTotal();
		
	}
	
	function updateTotal () {
		
		$MtnNodeBudget = Doctrine_Core::getTable('MtnNodeBudget')->find($this->mtn_node_budget_id);
		$MtnNodeBudget->mtn_node_budget_total = Doctrine_Core::getTable('MtnNodeBudget')->getTotal($this->mtn_node_budget_id);
		$MtnNodeBudget->save();
	
	}
	

}
