<?php

/**
 * MtnWorkOrder
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class MtnWorkOrder extends BaseMtnWorkOrder {

    public function preHydrate(Doctrine_Event $event) {

        $data = $event->data;

        if (isset($data['mtn_work_order_id'])) {

            ////////////SUMA LAS TAREAS DEL WORK ORDER Y LOS COMPONENTES DE CADA TAREA/////////////

            $q = Doctrine_Query::create()
                    ->from('MtnWorkOrderTask mwot')
                    ->where('mwot.mtn_work_order_id = ?', $data['mtn_work_order_id'])
            ;

            $results = $q->execute();
            $suma_task = 0;
            $sumCantPrice = 0;
            foreach ($results as $result) {

                $suma_task = $suma_task + $result->mtn_work_order_task_price;

                $q = Doctrine_Query::create()
                        ->select('wotc.*, plc.mtn_price_list_component_price, co.mtn_component_name, cowo.mtn_component_name, ctco.mtn_component_type_name, ctcowo.mtn_component_type_name')
                        ->from('MtnWorkOrderTaskComponent wotc')
                        ->leftJoin('wotc.MtnPriceListComponent plc')
                        ->leftJoin('plc.MtnComponent co')
                        ->leftJoin('co.MtnComponentType ctco')
                        ->leftJoin('wotc.MtnComponent cowo')
                        ->leftJoin('cowo.MtnComponentType ctcowo')
                        ->where('wotc.mtn_work_order_task_id = ?', $result->mtn_work_order_task_id)
                        ->orderBy('wotc.mtn_work_order_component_amount DESC');

                $results_component = $q->execute();
                foreach ($results_component as $component) {

                    $cant = $component->mtn_work_order_component_amount;
                    $price = $component->mtn_work_order_component_price;

                    $sumCantPrice = $sumCantPrice + ($cant * $price); //MULTIPLICA LA CANTIDAD POR EL VALOR Y LE SUMA TODOS LOS COMPONENTES
                }
                $suma_task = $suma_task + $sumCantPrice;
            }


            /////////////////////OTROS COSTOS //////////////////////

            $q = Doctrine_Query::create()
                    ->from('MtnWorkOrderOtherCosts mwooc')
                    ->where('mwooc.mtn_work_order_id = ?', $data['mtn_work_order_id'])
            ;
            $results = $q->execute();
            $otherCostsSum = 0;
            foreach ($results as $result) {
                $otherCostsSum = $otherCostsSum + $result->mtn_work_order_other_costs_costs; //SUMA LOS OTROS COSTOS BUSCANDO POR MTN_WORK_ORDER_ID EN LA TABLA MtnWorkOrderOtherCosts
            }


            $data['total_task'] = $suma_task;
            $data['total_other_costs'] = $otherCostsSum;


            $data['total_work_order'] = ($suma_task + $otherCostsSum);
            $data['total_work_order_iva'] = ($suma_task + $otherCostsSum) * 1.19;
            $event->data = $data;
        }
    }

//    function postDelete() {
//
//        $this->preHydrate();
//        
//        
//    }
//
//    function postInsert() {
//
//        $this->preHydrate();
//    }
//
//    function postUpdate() {
//        $this->preHydrate();
//    }

}
