<?php

/**
 * NetworkFo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class NetworkFo extends BaseNetworkFo
{

    public function preHydrate ( Doctrine_Event $event )
    {

        $data = $event->data;

        $tec_estados = array ( 1 => 'Buena' , 2 => 'Mala' , 3 => 'En Reparacion' );
        $com_estados = array ( 1 => 'Libre' , 2 => 'Ocupada' , 3 => 'Reservada' );
        $servicios = array ( 0 => null ,
            1 => 'Internet' ,
            2 => 'TV' ,
            3 => 'Telefonia' ,
            4 => 'Internet+TV' ,
            5 => 'Internet+Telefonia' ,
            6 => 'TV+Telenofia' ,
            7 => 'Internet+Telefonia+TV' );

        $data[ 'network_fo_status_name' ] = $tec_estados[ $data[ 'network_fo_status' ] ];
        $data[ 'network_fo_commercial_status_name' ] = $com_estados[ $data[ 'network_fo_commercial_status' ] ];
        $data[ 'network_fo_service_name' ] = ($data[ 'network_fo_service' ] != null ? $servicios[ $data[ 'network_fo_service' ] ] : null);

        $event->data = $data;
    }

}
